# Generated by Django 6.0.4 on 2026-04-22 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weeks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('field_type', models.CharField(choices=[('boolean', 'Yes / No toggle'), ('short_text', 'Short text'), ('long_text', 'Long text')], default='boolean', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_checkins', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_checkins', to='weeks.week')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boolean_answer', models.BooleanField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='growth.checkinquestion')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='growth.journeycheckin')),
            ],
        ),
        migrations.CreateModel(
            name='MidweekReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('going_well', 'Going well'), ('struggling', 'Struggling'), ('not_started', 'Not started')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midweek_reflections', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midweek_reflections', to='weeks.week')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaturdayTakeaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_step', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_takeaways', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_takeaways', to='weeks.week')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='journeycheckin',
            constraint=models.UniqueConstraint(fields=('user', 'week'), name='unique_journey_checkin_per_user_week'),
        ),
        migrations.AddConstraint(
            model_name='checkinanswer',
            constraint=models.UniqueConstraint(fields=('checkin', 'question'), name='unique_answer_per_checkin_question'),
        ),
        migrations.AddConstraint(
            model_name='midweekreflection',
            constraint=models.UniqueConstraint(fields=('user', 'week'), name='unique_midweek_reflection_per_user_week'),
        ),
        migrations.AddConstraint(
            model_name='saturdaytakeaway',
            constraint=models.UniqueConstraint(fields=('user', 'week'), name='unique_saturday_takeaway_per_user_week'),
        ),
    ]
