# Generated by Django 6.0.4 on 2026-04-22 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weeks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('scripture_references', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_words', to=settings.AUTH_USER_MODEL)),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_word', to='weeks.week')),
            ],
            options={
                'ordering': ['-week__start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='study_resources/')),
                ('external_link', models.URLField(blank=True)),
                ('weekly_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='studies.weeklyword')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
