# Generated by Django 6.0.4 on 2026-04-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyword',
            name='title',
        ),
    ]
